name: CI
on: [push]

defaults:
  run:
    shell: bash

jobs:
  coverage-grcov:
    name: Grcov

    strategy:
      fail-fast: false

      matrix:
        toolchain: [nightly]
        target: [x86_64-apple-darwin]
        os: [macos-latest]

        include:
          - toolchain: nightly
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - toolchain: nightly
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          components: llvm-tools-preview
          default: true

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          command: test
          args: --verbose --target ${{ matrix.target }}
        env:
          RUSTFLAGS: -Zinstrument-coverage
          LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"

      - name: Install grcov
        uses: actions-rs/install@v0.1
        with:
          crate: grcov
          version: latest

      - name: Run grcov
        run: grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

      - run: cat lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          name: ${{ matrix.toolchain }}-${{ matrix.target }}
          fail_ci_if_error: true
          env_vars: OS,TARGET,TOOLCHAIN,JOB
          files: ./lcov.info
        env:
          JOB: ${{ github.job }}
          OS: ${{ matrix.os }}
          TARGET: ${{ matrix.target }}
          TOOLCHAIN: ${{ matrix.toolchain }}
